### PR TITLE
Mepts 932 add datim code column

### PR DESCRIPTION
**Pull request by helderjosue**

### CODE REVIEW

**Review by iteliolucas — CHANGES_REQUESTED** [review]
Is there a reason to keep commented code in the Setup file?
If not I suggest you remove those lines.

**Comment by helderjosue** [comment]
I think we should keep it so, because the commented datasets still mapped on the template; it means, somehow we still need it

**Review by iteliolucas — CHANGES_REQUESTED** [review]
The reasons for that are:
1. This setup is for MER report not IMER report
2. This Setup is not being used

You should revert the changes on this file and go for **SetupCombinedImErReport.java**

**Comment by helderjosue** [comment]
Regarding the commented code on semi anual report, I’ll just uncomment instead of removing it.

**Review by iteliolucas — APPROVED** [review]

**Comment by iteliolucas** [comment]
Thanks @helderjosue agreed as per our early conversation

**Review by cfaife — APPROVED** [review]

**Pull request merged**
