### PR TITLE
MEPTS-504: Fix Transfered-Out Query in IM-ER4 for CCS DB Differences

### PR DESCRIPTION
**Pull request by JoaoCumbula**

### CODE REVIEW

**Comment by ynurmahomed** [comment]
@JoaoCumbula This PR also changes the logic for the suspended query. 

Is that intended?

https://github.com/jembi/openmrs-module-eptsreports/blob/57cb9779ad9e20639a2eb6b6dc459cc9d7620fea/api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/HivCohortQueries.java#L292-L297

**Comment by ynurmahomed** [comment]
@JoaoCumbula
 
Screenshot from 2020-05-27 15-28-26

:thinking:

**Comment by JoaoCumbula** [comment]
Is there anything missing in code @ynurmahomed ?

**Comment by ynurmahomed** [comment]
No just wondering a about why it says `22 days ago`

**Pull request merged**
